### ISSUE TITLE
Wrapped component is moved upwards

### ISSUE THREAD

**Issue by Manhazito** [mohebifar/react-native-copilot#108]
**Current Behaviour**
I'm using react-native-scrollable-tab-view with a custom tab bar component. I wrapped that component using:
`export default copilot({
   androidStatusBarVisible: true
 })(GoTabBar)`

Just doing those steps leads to the scrollable tab view to be moved upward from its original place (see image below — the left image is the correct behaviour, without the use of copilot, the right one is after using copilot). The pink bottom bar is the GoTabBar component, that is wrapped using copilot.

**Expected Behaviour**
The parent component should not move from its original place.

![error](https://user-images.githubusercontent.com/5558890/53605469-7df47880-3baf-11e9-86ce-39d836686720.jpg)

**Environment**
- Device: Xiaomi mi a2
- OS: Android
- `react-native-copilot`: [v2.4.1]
- `react-native`: [v0.58.5]
- `react-native-svg`: [v9.2.4]

**Comment by mohebifar** [comment]
Hmm... The wrapper gets a `{ flex: 1 }` only ([See the code here](https://github.com/okgrow/react-native-copilot/blob/master/src/hocs/copilot.js#L172)). I could predict that there might be some cases where this won't work. Maybe we should add a `wrapperStyle` option to the HOC function? 🤔 A PR to fix that would be welcomed.
