### ISSUE TITLE
this.props.start() being called but not starting copilot.

### ISSUE THREAD

**Issue by sinewave440hz** [mohebifar/react-native-copilot#116]
**Current Behavior**
I have a Menu component wrapped in a copilot() and a Home screen wrapped in a copilot(). The home screen is contained in a react-navigation drawer. The menu component is the component shown when the drawer is open. I activate the tutorial by setting an asyncstorage variable `tutorialModeOn` in a menu available in the open drawer. The tutorial starts on the Menu component, but does not start on the Home screen next time it is in focus.

**Input Code**

I set up the following in componentDidMount() for the menu: 
```js
  componentDidMount() {
    this.focusListener = this.props.navigation.addListener('didFocus', async () => {
      if(this.props.navigation.state.isDrawerOpen) {
        const tutorialModeOn = await utils.getCurrentTutorialMode();
        if(tutorialModeOn) {
          this.props.start();
        }
      }
    });
  }
```

and in the Home component, similarly:

```js
 componentDidMount() {
    this.focusListener = this.props.navigation.addListener('didFocus', async () => {
      const parent = this.props.navigation.dangerouslyGetParent();
      const grandparent = parent && parent.dangerouslyGetParent();
      const isDrawerOpen = grandparent && grandparent.state && grandparent.state.isDrawerOpen;
      if(!isDrawerOpen) {
        const tutorialModeOn = await utils.getCurrentTutorialMode();
        if(tutorialModeOn) {
          this.props.start();
        }
      }
    });
  }
```

**Expected behavior/code**
When the Home component receives focus it should activate the tutorial. this.props.start() is called, but doesn't start the tutorial. If I show the Home component first, the menu component's start call is activated next time it receives focus, but doesn't start either. It seems as if the start call called first is interfering with the other start call on the same Drawer Navigator. If so, how I can I prevent this?

**Environment**
- Device: [e.g. iPhone 7]
- OS: [e.g. iOS12]
- `react-native-copilot`: [e.g. v2.4.3]
- `react-native`: [e.g. v0.57.8]
- `react-native-svg`: [e.g. v9.2.4]

**Possible Solution**
Perhaps implementing this.props.stop() would solve this.

**Comment by sinewave440hz** [comment]
Maybe nobody else has had this issue, but I solved it by hooking into the DRAWER_OPENED and DRAWER_CLOSED actions in react navigation in the end, running this.props.start() there as appropriate.

**Comment by helloeyesimple** [comment]
@sinewave440hz can you share your code?

**Comment by sinewave440hz** [comment]
This is what I have in my menu component, I left in our code for tracking if we are in tutorial mode and whether the copilot has already run, as an example.
```
    const defaultGetStateForAction = this.props.navigation.router.getStateForAction;
    this.props.navigation.router.getStateForAction = (action: any, state: any) => {
      if (state && action.type === 'Navigation/DRAWER_OPENED') {
        asyncStorageMethods.getCurrentTutorialMode().then(async (mode) => {
          const hasAlreadyRun = await asyncStorageMethods.getStepsDone(StepsDone.Menu);
          if(mode && !hasAlreadyRun) {
            this.setState({tutorialModeOn: true})
            this.props.start();
          };
        });
      }
      // Make sure to reset the selected item every time navigation is toggled
      if (state && action.type === 'Navigation/TOGGLE_DRAWER') {
        this.selectItem(null);
      }
      return defaultGetStateForAction(action, state);
    };
```
