### ISSUE TITLE
componentWillReceiveProps is deprecated and will be removed in the next major version.

### ISSUE THREAD

**Issue by Brlja** [mohebifar/react-native-copilot#159]
**Current Behavior**
On React-Native 0.60+ deprecation warning is thrown.  
```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: ConnectedCopilotStep, CopilotModal

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Environment**
- `react-native-copilot`: @latest
- `react-native`: 0.60.5

**Possible Solution**
Remove code from deprecated methods in ConnectedCopilotStep, CopilotModal

**Comment by danieltov** [comment]
### Possible implementation of solution
https://hackernoon.com/replacing-componentwillreceiveprops-with-getderivedstatefromprops-c3956f7ce607

**Comment by spencer-evans-pnt** [comment]
I recommend we change to `componentDidUpdate`, as suggested in [this React post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html).
