### ISSUE TITLE
The highlight path doesn't fit with my text

### ISSUE THREAD

**Issue by 15110011** [mohebifar/react-native-copilot#160]
**Current Behavior**
- The highlight path doesn't fit with my **WalkthroughableText**
**Environment**
- Device: Nexus 5 API 27
- `react-native-copilot`:  v2.4.6
- `react-native`: v0.59.10
- `react-native-svg`: v9.9.4
**Code**
```
        <CopilotStep
          text='Here goes your profile picture!'
          order={1}
          name='secondText'
        >
          <WalkthroughableText>DASDASDASDSAD</WalkthroughableText>
        </CopilotStep>
```
**Image**
![image](https://user-images.githubusercontent.com/37216098/70897688-b32a6400-2025-11ea-8e90-2d7fb9676192.png)

**Comment by sasivarnan** [comment]
I was also facing similar issue. I fixed it by using the `verticalOffset` property. 

Read more about that usage of the `verticalOffset` property over [here](https://github.com/mohebifar/react-native-copilot#adjust-vertical-position).

**Comment by 15110011** [comment]
@sasivarnan Thank for your help.

**Comment by ncoen97** [comment]
@15110011  You should close the issue!
