### ISSUE TITLE
App crashing after some times

### ISSUE THREAD

**Issue by amitiwary999** [mohebifar/react-native-copilot#182]
**Current Behavior**
After props.start() call if the user doesn't do anything and app remains opens, app crashes after 10-15 sec.

**Input Code**
- REPL or Repo link if applicable:

```js
    <View style={{position:'absolute', height: screenHeight, width: deviceWidth }}>
        <View>
          <CopilotStep  text="Here goes your profile picture!" order={2} name="secondText">
            <WalkthroughableImage
              source={{ uri: 'https://pbs.twimg.com/profile_images/527584017189982208/l3wwN-l-_400x400.jpeg' }}
              style={styles2.profilePhoto}
            />
          </CopilotStep>

        </View>
        <View style={styles2.row}>
          <CopilotStep text="Here is an item in the corner of the screen." order={3} name="thirdText">
            <WalkthroughableText style={styles2.tabItem}>
              <View style={styles2.row}></View>
            </WalkthroughableText>
          </CopilotStep>
        </View>
      </View>

export default copilot({
  animated: true, // Can be true or false
  overlay: 'svg', // Can be either view or svg
})(StoryScreen);
```

**Expected behavior/code**
App should not crash even if user not interact with app for sometimes.

**Environment**
- Device: moto g5
- OS: android 8
- `react-native-copilot`: 2.4.7
- `react-native`: 0.62
- `react-native-svg`: 12.1.0

**Possible Solution**

**Additional context/Screenshots**

Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
    in SvgMask (at CopilotModal.js:243)
    in CopilotModal (at copilot.js:202)
    in Copilot (at SceneView.tsx:98)
    in SceneView (at useDescriptors.tsx:125)
    in CardContainer (at CardStack.tsx:561)
    in CardStack (at StackView.tsx:418)
    in KeyboardManager (at StackView.tsx:416)
    in Context.Consumer (at StackView.tsx:414)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at Navigation.js:73)
    in createHomeStack (at SceneView.tsx:98)
    in SceneView (at useDescriptors.tsx:125)
    in DrawerView (at DrawerView.tsx:208)
    in DrawerView (at createDrawerNavigator.tsx:44)
    in DrawerNavigator (at Navigation.js:85)
    in createDrawer (at SceneView.tsx:98)
    in SceneView (at useDescriptors.tsx:125)
    in CardContainer (at CardStack.tsx:561)
    in CardStack (at StackView.tsx:418)
    in KeyboardManager (at StackView.tsx:416)
    in Context.Consumer (at StackView.tsx:414)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at Navigation.js:50)
    in Navigation (at App.js:111)
    in App (at reactnativehybrid/​index.js:18)
    in RNRedux (at renderApplication.js:45)

**Comment by dsemennyuk** [comment]
@amitiwary999 Did solve it somehow? The same issue there. Maybe you know some alternatives?

**Comment by Nilesh8451** [comment]
@amitiwary999 did you fine any solution on this?? @dsemennyuk

**Comment by amitiwary999** [comment]
@Nilesh8451 I don't remember the solution. I should have posted it when I fixed it but now I can't recall it.
