### ISSUE TITLE
Has any one   tried to use this library along with react navigation

### ISSUE THREAD

**Issue by KaulSalil** [mohebifar/react-native-copilot#75]
Hi 
This library fits my use case very well ,unfortunately some of the views that i need highlighted are on different screens/routes/navigators/components .  They are not a single component . One of  the views that i need to highlight is in side drawer  . The first screenshot  contains the top tab bar in which i want to highlight all the individual items and the second screen shot contains the drawer which i want to high light . We are using react navigation . Kindly help please 

![screen shot 2018-09-14 at 7 32 39 pm](https://user-images.githubusercontent.com/8721680/45554935-180c7280-b855-11e8-91f7-e37ba848fb1f.png)

![screen shot 2018-09-14 at 7 33 11 pm](https://user-images.githubusercontent.com/8721680/45554928-15aa1880-b855-11e8-9a23-517207fe7b65.png)

**Comment by mohebifar** [comment]
I believe it should be doable using the step change event listener and updating rn-navigation's state accordingly. I am currently working on a new example app that includes react-navigation. However, I can't estimate when I'll be able to finish it.

**Comment by kaulsalil88** [comment]
i am also thinking on the similar lines will update you  with the progress i make in this approach .

**Comment by pribeh** [comment]
I'm going to give this a stab this weekend. I'll report back as well.

**Comment by kaulsalil88** [comment]
didnt have much luck with this till now .

**Comment by pribeh** [comment]
@RichardLitt Not yet. I'm also using React Native Navigation, but the logic shouldn't be that different. I'll likely be able to get to it next week.

**Comment by z98361** [comment]
any update? i can see log:  console.log(`Current step is: ${step.name}`) but nothing guide to show

**Comment by shamanking** [comment]
I have same issue. It's nice for the first screen:

![screen shot 2018-11-12 at 4 48 51 pm](https://user-images.githubusercontent.com/5752503/48339644-42cf4780-e69b-11e8-89c7-ed62b5d51080.png)
![screen shot 2018-11-12 at 4 49 19 pm](https://user-images.githubusercontent.com/5752503/48339645-4367de00-e69b-11e8-9c38-c8a06f4ad051.png)

but when I navigate to another screen, I want to display tooltip at text _AAAAA_, but it looks weird. If I set position Text _AAAAA_ at the bottom, even I can not see the Tooltip

![screen shot 2018-11-12 at 4 50 56 pm](https://user-images.githubusercontent.com/5752503/48339818-a35e8480-e69b-11e8-8cdd-1ef9bec32d59.png)

**Comment by shamanking** [comment]
I have solution for react-navigation, we need to calculate for obj.left and obj.top
In CopilotModal.js, function _animateMove()
```
async _animateMove(obj = {}): void {
    const layout = await this.measure();
    obj.left = obj.left % Dimensions.get('window').width
    obj.top = obj.top % Dimensions.get('window').height

    if (!this.props.androidStatusBarVisible && Platform.OS === 'android') {
      obj.top -= StatusBar.currentHeight; // eslint-disable-line no-param-reassign
    }
...
```

**Comment by dianbagus96** [comment]
hi, is there any solution for this ?

**Comment by RichardLitt** [comment]
@dianbagus96 Not at the moment. Anyone is free to make a PR, at this point, though. :)

**Comment by obiwankenoobi** [comment]
@shamanking awesome workaround

**Comment by blazk0** [comment]
> I believe it should be doable using the step change event listener and updating rn-navigation's state accordingly. I am currently working on a new example app that includes react-navigation. However, I can't estimate when I'll be able to finish it.

Hello, is there anyway i can use it with react navigation header icon and bottom tab nav icons ?
